export default {
  GET_CVS: 'GET_CVS',
  GET_CV: 'GET_CV',
  CREATE_CV: 'CREATE_CV',
  UPDATE_CV: 'UPDATE_CV',
  DELETE_CV: 'DELETE_CV',
  GENERATE_DOCX: 'GENERATE_DOCX',
  UPDATE_PROFILE_IMAGE: 'UPDATE_PROFILE_IMAGE',
};
